# latest
update

# add repository
tap homebrew/binary || true
tap caskroom/cask || true
tap homebrew/dupes || true
tap homebrew/science || true
tap jimbojsb/launchrocket || true

# install package

install ack || brew upgrade ack || true
install ant || brew upgrade ant || true
install apple-gcc42 || brew upgrade apple-gcc42 || true
install atk || brew upgrade atk || true
install autoconf || brew upgrade autoconf || true
install automake || brew upgrade automake || true
install bash || brew upgrade bash || true
install boost || brew upgrade boost || true
install brew-cask || brew upgrade brew-cask || true
install cairo || brew upgrade cairo || true
install cloog || brew upgrade cloog || true
install cmatrix || brew upgrade cmatrix || true
install colordiff || brew upgrade colordiff || true
install cscope || brew upgrade cscope || true
install emacs || brew upgrade emacs || true
install fontconfig || brew upgrade fontconfig || true
install fontforge || brew upgrade fontforge || true
install fortune || brew upgrade fortune || true
install freetype || brew upgrade freetype || true
install gdbm || brew upgrade gdbm || true
install gdk-pixbuf || brew upgrade gdk-pixbuf || true
install gettext || brew upgrade gettext || true
install ghc || brew upgrade ghc || true
install git || brew upgrade git || true
install git-flow || brew upgrade git-flow || true
install giter8 || brew upgrade giter8 || true
install glib || brew upgrade glib || true
install gmp || brew upgrade gmp || true
install go --cross-compile-all || brew upgrade go || true
install gobject-introspection || brew upgrade gobject-introspection || true
install gradle || brew upgrade gradle || true
install groovy || brew upgrade groovy || true
install gtk+ || brew upgrade gtk+ || true
install gtksourceview || brew upgrade gtksourceview || true
install harfbuzz || brew upgrade harfbuzz || true
install haskell-platform || brew upgrade haskell-platform || true
install htop-osx || brew upgrade htop-osx || true
install hub || brew upgrade hub || true
install icu4c || brew upgrade icu4c || true
install intltool || brew upgrade intltool || true
install isl || brew upgrade isl || true
install jmeter || brew upgrade jmeter || true
install jpeg || brew upgrade jpeg || true
install less || brew upgrade less || true
install libevent || brew upgrade libevent || true
install libffi || brew upgrade libffi || true
install libmpc || brew upgrade libmpc || true
install libpng || brew upgrade libpng || true
install libtiff || brew upgrade libtiff || true
install libtool || brew upgrade libtool || true
install libyaml || brew upgrade libyaml || true
install lv || brew upgrade lv || true
install macvim || brew upgrade macvim || true
install markdown || brew upgrade markdown || true
install maven || brew upgrade maven || true
install meld || brew upgrade meld || true
install mercurial || brew upgrade mercurial || true
install mpfr || brew upgrade mpfr || true
install mysql || brew upgrade mysql || true
install neon || brew upgrade neon || true
install nkf || brew upgrade nkf || true
install nmap || brew upgrade nmap || true
install node || brew upgrade node || true
install openssl || brew upgrade openssl || true
install ossp-uuid || brew upgrade ossp-uuid || true
install pango || brew upgrade pango || true
install pcre || brew upgrade pcre || true
install pixman || brew upgrade pixman || true
install pkg-config || brew upgrade pkg-config || true
install play || brew upgrade play || true
install postgresql || brew upgrade postgresql || true
install pow || brew upgrade pow || true
install pstree || brew upgrade pstree || true
install py2cairo || brew upgrade py2cairo || true
install pygobject || brew upgrade pygobject || true
install pygtk || brew upgrade pygtk || true
install pygtksourceview || brew upgrade pygtksourceview || true
install python || brew upgrade python || true
install puthon3 || brew upgrade python3 || true
install rarian || brew upgrade rarian || true
install rbenv || brew upgrade rbenv || true
install readline || brew upgrade readline || true
install reattach-to-user-namespace || brew upgrade reattach-to-user-namespace || true
install ruby-build || brew upgrade ruby-build || true
install sbt || brew upgrade sbt || true
install scala || brew upgrade scala || true
install scons || brew upgrade scons || true
install source-highlight || brew upgrade source-highlight || true
install sqlite || brew upgrade sqlite || true
install subversion || brew upgrade subversion || true
install sysdig || brew upgrade sysdig || true
install the_silver_searcher || brew upgrade hte_silver_searcher || true
install tig || brew upgrade tig || true
install tmux || brew upgrade tmux || true
install tomcat || brew upgrade tomcat || true
install tree || brew upgrade tree || true
install vim || brew upgrade vim || true
install watch || brew upgrade watch || true
install wget || brew upgrade wget || true
install xctool || brew upgrade xctool || true
install xz || brew upgrade xz || true
install yuicompressor || brew upgrade yuicompressor || true
install z || brew upgrade z || true
install zsh || brew upgrade zsh || true
install zsh-completions || brew upgrade zsh-completions || true
install docker || brew upgrade docker || true
install boot2docker || brew upgrade boot2docker || true
install jenkins || brew upgrade jenkins || true
install coreutils || brew upgrade coreutils || true
install fsharp || brew upgrade fsharp || true
# brew cask
cask install alfred || cask upgrade alfred || true
cask install diffmerge || cask upgrade diffmerge || true
cask install rstudio || cask upgrade rstudio || true
cask install vagrant || cask upgrade vagrant || true
cask install vlc || cask upgrade vlc || true
cask install dash || cask upgrade dash || true
cask install p4merge || cask upgrade p4merge || true
cask install sourcetree || cask upgrade sourcetree || true
cask install virtualbox || cask upgrade virtualbox || true
cask install xquartz || cask upgrade xquartz || true
cask install xmind || cask upgrade xmind || true
cask install wireshark || cask upgrade wireshark || true
cask install google-drive || cask upgrade google-drive || true
cask install google-web-designer || cask upgrade google-web-designer || true
cask install keyremap4macbook || cask upgrade keyremap4macbook || true
cask install sublime-text || cask upgrade sublime-text || true
cask install skype || cask upgrade skype || true
cask install skitch || cask upgrade skitch || true
cask install bettertouchtool || cask upgrade bettertouchtool || true
cask install dropbox || cask upgrade dropbox || true
cask install evernote || cask upgrade evernote || true
cask install mendeley || cask upgrade mendeley || true
cask install mysql-workbench || cask upgrade mysql-workbench || true
cask install iterm2 || cask upgrade iterm2 || true
cask install appcleaner || cask upgrade appcleaner || true
cask install emacs || cask upgrade emacs || true
cask install launchrocket || cask upgrade launchrocket || true
