# latest
update

# update all
upgrade

# add repository
tap homebrew/binary
tap caskroom/cask
tap homebrew/dupes
tap homebrew/science
tap jimbojsb/launchrocket
tap peco/peco

# for X
cask install xquartz

# install package
install ack
install ant
install apple-gcc42
install atk
install autoconf
install automake
install bash
install boost
install brew-cask
install cairo
install cloog
install cmatrix
install colordiff
install cscope
install emacs
install fontconfig
install fontforge
install fortune
install freetype
install gdbm
install gdk-pixbuf
install gettext
install git
install git-flow
install giter8
install glib
install gmp
install go --cross-compile-all
install gobject-introspection
install gradle
install groovy
install gtk+
install gtksourceview
install harfbuzz
install haskell-platform
install htop-osx
install hub
install icu4c
install intltool
install isl
install jmeter
install jpeg
install less
install libevent
install libffi
install libmpc
install libpng
install libtiff
install libtool
install libyaml
install lv
install macvim
install markdown
install maven
install meld
install mercurial
install mpfr
install mysql
install neon
install nkf
install nmap
install node
install openssl
install ossp-uuid
install pango
install pcre
install pixman
install pkg-config
#install play
install postgresql
install pow
install pstree
install py2cairo
install pygobject
install pygtk
install pygtksourceview
install python
install rarian
install rbenv
install readline
install reattach-to-user-namespace
install ruby-build
install sbt
install scala
install scons
install source-highlight
install sqlite
install subversion
install sysdig
install the_silver_searcher
install tig
install tmux
install tomcat
install tree
install vim
install watch
install wget
install xctool
install xz
install yuicompressor
install z
install zsh
install zsh-completions
install docker
install boot2docker
install jenkins
install coreutils
install fsharp
install zlib
install pyenv
install typesafe-activator
install peco
install direnv
install bzr

# brew cask
cask install alfred
cask install diffmerge
cask install rstudio
cask install vagrant
cask install vlc
cask install dash
cask install p4merge
cask install sourcetree
cask install virtualbox
cask install xmind
cask install wireshark
cask install google-drive
cask install google-web-designer
cask install --caskroom=/Applications google-chrome
cask install keyremap4macbook
cask install skype
cask install skitch
cask install bettertouchtool
cask install dropbox
cask install evernote
cask install mysqlworkbench
cask install iterm2
cask install appcleaner
cask install emacs
cask install launchrocket
cask install atom
cask install hyperswitch
cask install sophos-anti-virus-home-edition
cask install vmware-fusion
cask install airmail
cask install google-japanese-ime
cask install onyx
cask install eclipse-ide
## for alfred
cask alfred link

# cleanup
cleanup
